export const NFTs = [
  {
    Id: 1,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/vegan/annie-spratt-m1t-RJ1iCIU-unsplash.jpg",
    Edition: 371,
    Stock: 128,
    Title: "Fresh Vegetable",
    Price: "$10M",

    Avatar: "/images/avatar/newk3d.png",
    Author: "PHATBB",
    Likes: 652,
  },
  {
    Id: 2,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/vegan/1.jpg",
    Edition: 371,
    Stock: 128,
    Title: "Fresh Vegetable",
    Price: "$10M",
    Avatar: "/images/avatar/newk3d.png",
    Author: "PHATBB",
    Likes: 652,
  },
  {
    Id: 3,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/vegan/2.jpg",
    Edition: 371,
    Stock: 128,
    Title: "Fresh Vegetable",
    Price: "$10M",
    Avatar: "/images/avatar/newk3d.png",
    Author: "PHATBB",
    Likes: 652,
  },
  {
    Id: 4,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/vegan/3.jpg",
    Edition: 371,
    Stock: 128,
    Title: "Fresh Vegetable",
    Price: "$10M",
    Avatar: "/images/avatar/newk3d.png",
    Author: "PHATBB",
    Likes: 652,
  },
  {
    Id: 5,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/vegan/4.jpg",
    Edition: 371,
    Stock: 128,
    Title: "Fresh Vegetable",
    Price: "$10M",
    Avatar: "/images/avatar/newk3d.png",
    Author: "PHATBB",
    Likes: 652,
  },
  {
    Id: 6,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/vegan/6.jpg",
    Edition: 371,
    Stock: 128,
    Title: "Fresh Vegetable",
    Price: "$10M",
    Avatar: "/images/avatar/newk3d.png",
    Author: "PHATBB",
    Likes: 652,
  },
];
